FROM alpine
RUN apk update \
    && apk upgrade \
    && apk add --no-cache ca-certificates \
    && update-ca-certificates 2>/dev/null || true
ADD build/sanitizer /
EXPOSE 8080
ENTRYPOINT ["/sanitizer"]
